# Generated by Django 5.2 on 2025-04-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_ingredients_recipe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
