# Generated by Django 5.2 on 2025-05-12 03:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_connect4game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connect4Game',
            new_name='Connect4Result',
        ),
    ]
