# Generated by Django 5.2 on 2025-06-27 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_connect4game_connect4result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ramseyphoto',
            options={'ordering': ['-date_taken', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='ramseyphoto',
            name='caption',
            field=models.TextField(blank=True, help_text='Optional caption describing the photo'),
        ),
        migrations.AddField(
            model_name='ramseyphoto',
            name='date_taken',
            field=models.DateField(default=django.utils.timezone.now, help_text='When was this photo taken?'),
        ),
        migrations.AddField(
            model_name='ramseyphoto',
            name='title',
            field=models.CharField(default='Untitled Photo', max_length=200),
        ),
    ]
