# Generated by Django 5.2 on 2025-07-03 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_ramseyphoto_options_ramseyphoto_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramseyphoto',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ramseyphoto',
            name='date_taken',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
