# Generated by Django 5.2 on 2025-07-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('bread', 'Bread'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
