# Generated by Django 5.2 on 2025-09-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_reviewcategory_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
