# Generated by Django 5.2 on 2025-09-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_review_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
