# Generated by Django 5.2 on 2025-09-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ReviewCategory',
        ),
    ]
