# Generated by Django 5.2 on 2025-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_review_category_delete_reviewcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='place_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='place_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='place_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='place_website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
