# Generated by Django 5.2 on 2026-01-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_boardingexperience_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardingexperience',
            name='notes',
        ),
        migrations.AlterField(
            model_name='boardingexperience',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='boardingexperience',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boardingexperience',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='boardingexperience',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardingexperience',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
