# Generated by Django 5.2 on 2026-01-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_boardingexperience_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinerecord',
            name='document',
        ),
    ]
