# Generated by Django 5.2 on 2026-06-21 00:47

import django.db.models.deletion
from datetime import datetime
from django.db import migrations, models


def _parse_date(value):
    if not value:
        return None
    value = str(value).strip()
    for fmt in ('%Y-%m-%d', '%m/%d/%Y', '%d-%b-%Y', '%d-%B-%Y'):
        try:
            return datetime.strptime(value, fmt).date()
        except ValueError:
            continue
    return None


def migrate_legacy_reports(apps, schema_editor):
    PuppyMillFacility = apps.get_model('main', 'PuppyMillFacility')
    FacilityInspectionReport = apps.get_model('main', 'FacilityInspectionReport')

    for facility in PuppyMillFacility.objects.all().iterator():
        for report in facility.inspection_reports or []:
            url = report.get('url')
            if not url:
                continue
            FacilityInspectionReport.objects.get_or_create(
                facility=facility,
                report_url=url,
                defaults={
                    'inspection_date': _parse_date(report.get('date')),
                    'direct_count': report.get('direct') or 0,
                    'critical_count': report.get('critical') or 0,
                    'non_critical_count': report.get('non_critical') or 0,
                    'teachable_count': report.get('teachable') or 0,
                    'violations_parsed': False,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_puppymillfacility_incremental_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityInspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('report_url', models.URLField(max_length=500)),
                ('inspection_type', models.CharField(blank=True, max_length=80)),
                ('direct_count', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('non_critical_count', models.PositiveIntegerField(default=0)),
                ('teachable_count', models.PositiveIntegerField(default=0)),
                ('violations_parsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.puppymillfacility')),
            ],
            options={
                'ordering': ['-inspection_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FacilityViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('direct', 'Direct'), ('critical', 'Critical'), ('non_critical', 'Non-critical'), ('teachable', 'Teachable moment')], max_length=20)),
                ('section', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_repeat', models.BooleanField(default=False)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='main.puppymillfacility')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='main.facilityinspectionreport')),
            ],
            options={
                'ordering': ['-inspection_date', 'section'],
            },
        ),
        migrations.AddConstraint(
            model_name='facilityinspectionreport',
            constraint=models.UniqueConstraint(fields=('facility', 'report_url'), name='unique_facility_report_url'),
        ),
        migrations.AddIndex(
            model_name='facilityviolation',
            index=models.Index(fields=['facility', 'category'], name='main_facili_facilit_fa6bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityviolation',
            index=models.Index(fields=['-inspection_date'], name='main_facili_inspect_e13508_idx'),
        ),
        migrations.RunPython(migrate_legacy_reports, migrations.RunPython.noop),
    ]
