# Generated by Django 5.2 on 2026-06-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_facility_violations'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityinspectionreport',
            name='parse_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
