# Generated by Django 5.2 on 2026-06-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_report_parse_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('elixir', models.PositiveSmallIntegerField(default=0)),
                ('rarity', models.CharField(blank=True, max_length=30)),
                ('card_type', models.CharField(blank=True, max_length=30)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['elixir', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClashCenterSyncState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('is_running', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_cards_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_summary', models.JSONField(blank=True, default=dict)),
                ('progress', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Clash Center sync state',
            },
        ),
        migrations.CreateModel(
            name='ClashPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('tier', models.PositiveSmallIntegerField(default=0, help_text='Path of Legends league number (1–7), 0 if unknown')),
                ('last_battle_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClashBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_uid', models.CharField(max_length=80, unique=True)),
                ('battle_time', models.DateTimeField()),
                ('tier', models.PositiveSmallIntegerField(help_text='Path of Legends league number (1–7)')),
                ('player_tag', models.CharField(db_index=True, max_length=20)),
                ('opponent_tag', models.CharField(blank=True, db_index=True, max_length=20)),
                ('player_won', models.BooleanField()),
                ('player_cards', models.JSONField(help_text='Sorted list of 8 card IDs (player perspective)')),
                ('opponent_cards', models.JSONField(help_text='Sorted list of 8 card IDs')),
                ('player_crowns', models.PositiveSmallIntegerField(default=0)),
                ('opponent_crowns', models.PositiveSmallIntegerField(default=0)),
                ('arena_id', models.PositiveIntegerField(blank=True, null=True)),
                ('game_mode', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-battle_time'],
                'indexes': [models.Index(fields=['tier', '-battle_time'], name='main_clashb_tier_83d205_idx'), models.Index(fields=['player_tag', '-battle_time'], name='main_clashb_player__04cf8b_idx'), models.Index(fields=['opponent_tag', '-battle_time'], name='main_clashb_opponen_cd53b0_idx')],
            },
        ),
    ]
