"""
Django settings for bensbreads project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#LOAD .env file if exists for local dev
dotenv_file = os.path.join(BASE_DIR, ".env")
if os.path.isfile(dotenv_file):
    dotenv.load_dotenv(dotenv_file)

debug_bool = os.environ["debug_bool"].lower() == "true"
django_secret=os.environ["django_secret"]
db_url=os.environ["db_url"]
media_root=os.environ["media_root"]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = django_secret

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = debug_bool

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "main.apps.MainConfig",
    'widget_tweaks',
    'storages'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bensbreads.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                        BASE_DIR / 'main'/'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bensbreads.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
if debug_bool:
    db_config={
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
    }
else:
    db_config=dj_database_url.config(
        default=db_url
    )

DATABASES = {
    'default': db_config
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage' 

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

if DEBUG:
    MEDIA_ROOT = BASE_DIR / 'media'
    MEDIA_URL = '/media/'
else:
    # Use S3 for media
    STORAGES = {
        "default": {
            "BACKEND": 'storages.backends.s3boto3.S3Boto3Storage',
        },
        "staticfiles": {
            "BACKEND": 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }

    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = 'us-east-2'  # replace if needed
    AWS_QUERYSTRING_AUTH = False  # Makes uploaded files public (can be True for private media)
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/'

# Google Places API settings
GOOGLE_PLACES_API_KEY = os.environ.get('GOOGLE_PLACES_API_KEY', '')
# Use the same API key for Google Maps

# Email Configuration
# Resend (HTTP API, works on Render) - set RESEND_API_KEY in production
# Fall back to SMTP (Private Email) for local dev
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
if RESEND_API_KEY:
    EMAIL_BACKEND = 'main.email_backend.ResendBackend'
    # Use verified domain (admin@bensbreads.com) or onboarding@resend.dev for testing
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Ben\'s Breads <admin@bensbreads.com>')
else:
    EMAIL_BACKEND = 'main.email_backend.SMTPBackend'
    EMAIL_HOST = 'mail.privateemail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'admin@bensbreads.com'
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = 'admin@bensbreads.com'
    EMAIL_SSL_VERIFY = os.environ.get('EMAIL_SSL_VERIFY', 'false').lower() == 'true'

# Site URL for email links
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# Secret token for cron endpoints (e.g. daily reminder trigger from cron-job.org)
CRON_SECRET_TOKEN = os.environ.get('CRON_SECRET_TOKEN', 'yeet')

# Dog Watch: data collected by Render Cron Job (`python manage.py dog_watch_sync`).
# The web app only reads from the database.
DOG_WATCH_SYNC_INTERVAL_HOURS = int(os.environ.get('DOG_WATCH_SYNC_INTERVAL_HOURS', '24'))
DOG_WATCH_APHIS_DELAY_SECONDS = float(os.environ.get('DOG_WATCH_APHIS_DELAY_SECONDS', '1.5'))
DOG_WATCH_VIOLATIONS_BATCH_SIZE = int(os.environ.get('DOG_WATCH_VIOLATIONS_BATCH_SIZE', '40'))
DOG_WATCH_VIOLATIONS_MAX_BATCHES = int(os.environ.get('DOG_WATCH_VIOLATIONS_MAX_BATCHES', '50'))

# Clash Center: data collected by Render Cron Job (`python manage.py clash_center_sync`).
# The web app only reads from the database.
CLASH_ROYALE_API_TOKEN = os.environ.get('CLASH_ROYALE_API_TOKEN', '')
CLASH_ROYALE_API_BASE = 'https://proxy.royaleapi.dev/v1'
CLASH_CENTER_PLAYER_TAG = os.environ.get('CLASH_CENTER_PLAYER_TAG', '')
CLASH_CENTER_SYNC_INTERVAL_HOURS = float(os.environ.get('CLASH_CENTER_SYNC_INTERVAL_HOURS', '1'))
CLASH_CENTER_MAX_BATTLES_PER_SYNC = int(os.environ.get('CLASH_CENTER_MAX_BATTLES_PER_SYNC', '2500'))
CLASH_CENTER_API_DELAY_SECONDS = float(os.environ.get('CLASH_CENTER_API_DELAY_SECONDS', '0.4'))